### ISSUE TITLE
Upstream encryption and decryption functions from bmec to btcec

### ISSUE THREAD

**Issue by justusranvier** [monetas/bmd#7]
The upstream maintainer of btcec is willing to accept the EC encryption and decryption functionality into btcec.

Keeping all the EC code in the btcec package will allow it to be used instead of bmec and reduce maintenance requirements.

**Comment by ishbir** [comment]
Got it. Going to send them a pull request soon.

**Comment by ishbir** [comment]
Done: https://github.com/btcsuite/btcd/pull/375
Thanks!
